name: Test

on:
  push:
    branches:
      - feature/angular-unit-test
jobs:
  build:
    runs-on: ubuntu20
    
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version}}
          
      - name: Install Dependencies
        run: ls && npm i
        
      - name: Build
        run: npm run build -- --prod
        
      - name: Lint
        run: npm run lint
